### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Empi-Tech/paboo-pixel-gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [url](https://www.paboo.gr/pixel) mentioned in the metadata shows "Page not found". Please provide a valid url.
![Screenshot 2021-06-23 1 34 48 PM](https://user-images.githubusercontent.com/53495700/123164813-47019b00-d428-11eb-9ab2-e36498a09c9a.png)

**Comment by kostplu** [comment]
Hi,
We updated the metadata.yaml file to include the correct url.

Thanks,

**Comment by kostplu** [comment]
@praveena-pappu please check. Thanks!

**Comment by kostplu** [comment]
@praveena-pappu We have changed the url for the documentation could you please check again?
